main: main.java.me.avankziar.spigot.ash.AdvancedStoreHouse
name: AdvancedStoreHouse
version: 4
load: STARTUP
api-version: 1.16
description: a Storage System Plugin
author: Avankziar
softdepend: [Vault]
website: https://www.spigotmc.org/resources/advancedstorehouse.82337/